### ISSUE TITLE
Thanks for help: OSError: [Errno 2] No such file or directory when I run gclient sync

### ISSUE THREAD

**Issue by Cain1127** [strukturag/spreedme-iosapp#2]
Create symbolic link for quilt
Apply all quilt patches
Traceback (most recent call last):
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 108, in <module>
    main(sys.argv[1:])
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 100, in main
    apply_actions(ACTIONS)
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 82, in apply_actions
    subprocess.call(c_action)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
gclient sync -r webrtc_fork_v1.0
Hook 'bash sync_webrtc.sh webrtc_fork_v1.0' took 4777.57 secs

**Comment by ChristianNorbertBraun** [comment]
I run in exactly the same problem.
After checking out the repo, moving into `third_party` and running `gclient sync`.

```
Error: Command '/usr/bin/python src/strukturag-inhouse/apply-inhouse-patches.py' returned non-zero exit status 1 in /Users/christianbraun/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc
Create symbolic link for quilt
Apply all quilt patches
Traceback (most recent call last):
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 108, in <module>
    main(sys.argv[1:])
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 100, in main
    apply_actions(ACTIONS)
  File "src/strukturag-inhouse/apply-inhouse-patches.py", line 82, in apply_actions
    subprocess.call(c_action)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
gclient sync -r webrtc_fork_v1.0
Hook 'bash sync_webrtc.sh webrtc_fork_v1.0' took 1536.64 secs
```

**Comment by fancycode** [comment]
The script is trying to run `quilt` in this step, which doesn't seem to be available on your system.

@Ivansss do we need a special version of `quilt`?

**Comment by Ivansss** [comment]
Not really, `0.63 or newer` should be fine.
I will add `quilt` in prerequisites section.

**Comment by ChristianNorbertBraun** [comment]
@fancycode 
Thanks a lot after installing `quilt` the `gclient sync` step works just fine.
But I can't build the needed libs.
Seems like all the libs mentioned in `make-webrtc.sh` are missing.

```
No arguments supplied. Running build_fatty_nosim, which builds all (fat libs for debug and release).
-- building webrtc fat Debug without simulator
-- building AppRTCDemo for arm64 Debug
~/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc/src ~/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc
Updating projects from gyp files...
Traceback (most recent call last):
  File "webrtc/build/gyp_webrtc", line 100, in <module>
    gyp_rc = gyp.main(args)
  File "/Users/christianbraun/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc/src/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 525, in main
    return gyp_main(args)
  File "/Users/christianbraun/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc/src/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 510, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/christianbraun/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc/src/chromium/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2382, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: Multiple codesigning fingerprints for identity: iPhone Developer
ninja: Entering directory `out_ios64/Debug-iphoneos'
ninja: error: build.ninja:104: unexpected EOF
  description =
               ^ near here
~/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc
-- combining debug libraries for arm64
~/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc/src/out_ios64/Debug-iphoneos ~/Documents/repos/ios/apps/spreedme-iosapp/third_party/webrtc
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libjingle_peerconnection_objc.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libjingle_peerconnection.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libexpat.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libjsoncpp.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcrssl.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcrnspr.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcrnss.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libnss_static.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libsqlite_regexp.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libicui18n.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libicuuc.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libicudata.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcrnssckbi.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libjingle_media.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libyuv.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libusrsctplib.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_utility.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_coding_module.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libCNG.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcommon_audio.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libsystem_wrappers.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_encoder_interface.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libG711.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libG722.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libiLBC.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libiSAC.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_decoder_interface.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libiSACFix.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libPCM16B.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libred.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_opus.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libopus.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libneteq.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libmedia_file.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_video_coding.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_i420.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libcommon_video.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvideo_coding_utility.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_vp8.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvpx.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_vp9.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libwebrtc_common.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvideo_engine_core.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtp_rtcp.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libpaced_sender.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libremote_bitrate_estimator.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libbitrate_controller.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvideo_processing.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvoice_engine.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_conference_mixer.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_processing.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libaudio_device.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_sound.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libfield_trial_default.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libmetrics_default.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_xmllite.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_xmpp.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_base.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_base_approved.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: librtc_p2p.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvideo_capture_module.a (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: libvideo_capture_module_internal_impl.a (No such file or directory)
```

**Comment by fancycode** [comment]
@Ivansss looks like we need more help from you ;-)

The actual error seems to be `Multiple codesigning fingerprints for identity: iPhone Developer`, that's why it could not build the libraries.

**Comment by Ivansss** [comment]
Yes, that seems to be the problem.
@ChristianNorbertBraun how many iPhone Developer certificates you have in your keychain?

**Comment by ChristianNorbertBraun** [comment]
@Ivansss I have 3 certificates. How can I choose one of them?

**Comment by Ivansss** [comment]
First, find the list of valid code signing identities that are available by running this from the command line:

`security find-identity`

Then open  third_party/webrtc/src/build/common.gypi and search for the text ‘CODE_SIGN_IDENTITY’:

```
# iOS SDK wants everything for device signed
‘CODE_SIGN_IDENTITY[sdk=iphoneos*]‘: ‘iPhone Developer’
```

Switch the identity value with the one you chose from the valid identity list:

```
# iOS SDK wants everything for device signed
‘CODE_SIGN_IDENTITY[sdk=iphoneos*]‘: ‘iPhone Developer: John Doe (XXXXXXX)’
```

Source: http://ninjanetic.com/how-to-get-started-with-webrtc-and-ios-without-wasting-10-hours-of-your-life/

@ChristianNorbertBraun Let's see if this works

**Comment by ChristianNorbertBraun** [comment]
@Ivansss 
Worked like a charm! Thank you very much for your help.
Also the article you mentioned is really precious!
